#!/usr/bin/python3

import subprocess, sys

olip='89.188.16.159'
mss='1440'

vardir = '/var/lib/rf-dyn-ipip'
tunlis = vardir + '/tunnels.lis'
tundir = vardir + '/clients.d'


class ConfigError (Exception):
  def __init__(self, value):
    self.value = value
  def __str__(self):
    return repr(self.value)


def read_config (filename):
  try:
    ret = {}
    for l in open (filename, "r"):
      l = l.split ('#')[0].rstrip ()
      if l == '':
        continue
      i = l.split('=')
      if len (i) != 2:
        continue
      ret[i[0]]=i[1]
    return ret
  except FileNotFoundError:
    raise ConfigError ('Unable to open config file "%s"' % filename)


def inc_ip (ip):
  a = ip.split ('.')
  a[3] = int (a[3]) + 1

  return '%s.%s.%s.%d' % tuple (a)


def exec_cmd (cmd):
  try:
    print (cmd)
    subprocess.check_output (cmd, shell=True, stderr=subprocess.STDOUT)

    return True
  except subprocess.CalledProcessError:
    return False


def get_config_parameter (config_file, conf, parameter, default = None):
  try:
    return conf[parameter]
  except KeyError:
    if default != None:
      return default
    raise ConfigError ('Missing parameter "%s" in config file "%s"' % (parameter, config_file))

conf = read_config ('/etc/rf-dyn-ipip-server.conf')

for chain in ['IN_ipip', 'FW_ipip']:
  exec_cmd ('iptables -N %s'                  % chain)
  exec_cmd ('iptables -F %s'                  % chain)
  exec_cmd ('iptables -A %s -i ipip+ -j DROP' % chain)

  exec_cmd ('iptables -t mangle -F POSTROUTING')
  exec_cmd ('iptables -t mangle -A POSTROUTING -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss ' + mss)

for chain in ['IN_ip6ip', 'FW_ip6ip']:
  exec_cmd ('ip6tables -N %s'                   % chain)
  exec_cmd ('ip6tables -F %s'                   % chain)
  exec_cmd ('ip6tables -A %s -i ip6ip+ -j DROP' % chain)

  exec_cmd ('ip6tables -t mangle -F POSTROUTING')
  exec_cmd ('ip6tables -t mangle -A POSTROUTING -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss ' + mss)

olip = get_config_parameter ('/etc/rf-dyn-ipip-server.conf', conf, 'tunnel_ip')

for tmp in open (tunlis, 'r'):
  tmp = tmp.rstrip().split (' ')
  if len (tmp) != 7:
    continue
  (ipip, username, net, irip, ipip6, net6, irip6) = tmp

  tuncfgfile = tundir + '/' + username + '.conf'

  ilip  = inc_ip (irip)
  ilip6 = irip6 + ":1"
  irip6 = irip6 + ":0"

  for tmp in open (tuncfgfile, 'r'):
    tmp = tmp.rstrip().split (' ')
    if len (tmp) != 2:
      continue
    (orip, password) = tmp

    exec_cmd ('ip tunnel add %s mode ipip remote %s local %s' % (ipip, orip, olip)  )
    exec_cmd ('ip link set %s up'                             % (ipip)              )
    exec_cmd ('ip route flush dev %s'                         % (ipip)              )
    exec_cmd ('ip route add %s dev %s'                        % (net, ipip)         )
    exec_cmd ('ip route add %s dev %s'                        % (irip, ipip)        )
    exec_cmd ('ip addr  add %s dev %s'                        % (ilip, ipip)        )

    for i in ['IN', 'FW']:
      exec_cmd ('iptables -N %s_%s'                           % (i, ipip)           )
      exec_cmd ('iptables -F %s_%s'                           % (i, ipip)           )
      exec_cmd ('iptables -D %s_ipip -i %s -j %s_%s'          % (i, ipip, i, ipip)  )
      exec_cmd ('iptables -I %s_ipip -i %s -j %s_%s'          % (i, ipip, i, ipip)  )

    exec_cmd (  'iptables -I IN_%s -i %s       -s %s -d %s -p icmp -j ACCEPT'
              % (ipip, ipip, irip, ilip) )
    exec_cmd (  'iptables -I FW_%s -i %s       -s %s               -j ACCEPT'
              % (ipip, ipip, net) )

    exec_cmd ('ip tunnel add %s mode sit remote %s local %s'  % (ipip6, orip, olip) )
    exec_cmd ('ip link set %s up'                             % (ipip6)             )
    exec_cmd ('ip route add %s dev %s'                        % (net6, ipip6)       )
    exec_cmd ('ip route add %s dev %s'                        % (irip6, ipip6)      )
    exec_cmd ('ip addr  add %s dev %s'                        % (ilip6, ipip6)      )


    for i in ['IN', 'FW']:
      exec_cmd ('ip6tables -N %s_%s'                          % (i, ipip6)          )
      exec_cmd ('ip6tables -F %s_%s'                          % (i, ipip6)          )
      exec_cmd ('ip6tables -D %s_ip6ip -i %s -j %s_%s'        % (i, ipip6, i, ipip6))
      exec_cmd ('ip6tables -I %s_ip6ip -i %s -j %s_%s'        % (i, ipip6, i, ipip6))

    exec_cmd (  'ip6tables -I IN_%s -i %s       -s %s -d %s -p icmpv6 -j ACCEPT'
              % (ipip6, ipip6, irip6, ilip6) )
    exec_cmd (  'ip6tables -I FW_%s -i %s       -s %s               -j ACCEPT'
              % (ipip6, ipip6, net6) )
